steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/bidding-analysis:latest", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/bidding-analysis:latest"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "bidding-analysis"
      - "--image"
      - "gcr.io/$PROJECT_ID/bidding-analysis:latest"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--set-env-vars"
      - "DATABASE_URL=${_DATABASE_URL},DB_HOST=${_DB_HOST},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},DB_NAME=${_DB_NAME},DB_PORT=${_DB_PORT},OPENAI_API_KEY=${_OPENAI_API_KEY},ALLOWED_ORIGINS=${_ALLOWED_ORIGINS}"

substitutions:
  _DATABASE_URL: "${_DATABASE_URL}"
  _DB_HOST: "${_DB_HOST}"
  _DB_USER: "${_DB_USER}"
  _DB_PASSWORD: "${_DB_PASSWORD}"
  _DB_NAME: "${_DB_NAME}"
  _DB_PORT: "${_DB_PORT}"
  _OPENAI_API_KEY: "${_OPENAI_API_KEY}"
  _ALLOWED_ORIGINS: "https://bidding-analysis.web.app,https://bidding-analysis.firebaseapp.com"

options:
  logging: CLOUD_LOGGING_ONLY
