// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/bidding.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BidRequest represents an incoming bid request
type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserSegment   *UserSegment           `protobuf:"bytes,3,opt,name=user_segment,json=userSegment,proto3" json:"user_segment,omitempty"`
	GeoLocation   *GeoLocation           `protobuf:"bytes,4,opt,name=geo_location,json=geoLocation,proto3" json:"geo_location,omitempty"`
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,5,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FloorPrice    float64                `protobuf:"fixed64,7,opt,name=floor_price,json=floorPrice,proto3" json:"floor_price,omitempty"`
	Keywords      []string               `protobuf:"bytes,8,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_api_proto_bidding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *BidRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BidRequest) GetUserSegment() *UserSegment {
	if x != nil {
		return x.UserSegment
	}
	return nil
}

func (x *BidRequest) GetGeoLocation() *GeoLocation {
	if x != nil {
		return x.GeoLocation
	}
	return nil
}

func (x *BidRequest) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *BidRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BidRequest) GetFloorPrice() float64 {
	if x != nil {
		return x.FloorPrice
	}
	return 0
}

func (x *BidRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

// BidResponse contains the optimal bid price and confidence
type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidPrice      float64                `protobuf:"fixed64,1,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Strategy      string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	FraudRisk     bool                   `protobuf:"varint,4,opt,name=fraud_risk,json=fraudRisk,proto3" json:"fraud_risk,omitempty"`
	PredictionId  string                 `protobuf:"bytes,5,opt,name=prediction_id,json=predictionId,proto3" json:"prediction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_api_proto_bidding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{1}
}

func (x *BidResponse) GetBidPrice() float64 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (x *BidResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *BidResponse) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *BidResponse) GetFraudRisk() bool {
	if x != nil {
		return x.FraudRisk
	}
	return false
}

func (x *BidResponse) GetPredictionId() string {
	if x != nil {
		return x.PredictionId
	}
	return ""
}

// UserSegment represents audience segmentation data
type UserSegment struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SegmentId             string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Category              string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	EngagementScore       float64                `protobuf:"fixed64,3,opt,name=engagement_score,json=engagementScore,proto3" json:"engagement_score,omitempty"`
	ConversionProbability float64                `protobuf:"fixed64,4,opt,name=conversion_probability,json=conversionProbability,proto3" json:"conversion_probability,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserSegment) Reset() {
	*x = UserSegment{}
	mi := &file_api_proto_bidding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSegment) ProtoMessage() {}

func (x *UserSegment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSegment.ProtoReflect.Descriptor instead.
func (*UserSegment) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{2}
}

func (x *UserSegment) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *UserSegment) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UserSegment) GetEngagementScore() float64 {
	if x != nil {
		return x.EngagementScore
	}
	return 0
}

func (x *UserSegment) GetConversionProbability() float64 {
	if x != nil {
		return x.ConversionProbability
	}
	return 0
}

// GeoLocation represents geographical data
type GeoLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoLocation) Reset() {
	*x = GeoLocation{}
	mi := &file_api_proto_bidding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoLocation) ProtoMessage() {}

func (x *GeoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoLocation.ProtoReflect.Descriptor instead.
func (*GeoLocation) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{3}
}

func (x *GeoLocation) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GeoLocation) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GeoLocation) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GeoLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// DeviceInfo represents device and browser information
type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceType    string                 `protobuf:"bytes,1,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"` // mobile, desktop, tablet
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Browser       string                 `protobuf:"bytes,3,opt,name=browser,proto3" json:"browser,omitempty"`
	IsMobile      bool                   `protobuf:"varint,4,opt,name=is_mobile,json=isMobile,proto3" json:"is_mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_api_proto_bidding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceInfo) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *DeviceInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *DeviceInfo) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *DeviceInfo) GetIsMobile() bool {
	if x != nil {
		return x.IsMobile
	}
	return false
}

// BidHistoryRequest for querying historical bid data
type BidHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidHistoryRequest) Reset() {
	*x = BidHistoryRequest{}
	mi := &file_api_proto_bidding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidHistoryRequest) ProtoMessage() {}

func (x *BidHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidHistoryRequest.ProtoReflect.Descriptor instead.
func (*BidHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{5}
}

func (x *BidHistoryRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *BidHistoryRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *BidHistoryRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *BidHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BidHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// BidHistoryResponse contains historical bid data
type BidHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bids          []*BidRecord           `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidHistoryResponse) Reset() {
	*x = BidHistoryResponse{}
	mi := &file_api_proto_bidding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidHistoryResponse) ProtoMessage() {}

func (x *BidHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidHistoryResponse.ProtoReflect.Descriptor instead.
func (*BidHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{6}
}

func (x *BidHistoryResponse) GetBids() []*BidRecord {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *BidHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// BidRecord represents a single bid record
type BidRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidId         string                 `protobuf:"bytes,1,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	CampaignId    string                 `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	BidPrice      float64                `protobuf:"fixed64,3,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	WinPrice      float64                `protobuf:"fixed64,4,opt,name=win_price,json=winPrice,proto3" json:"win_price,omitempty"`
	Won           bool                   `protobuf:"varint,5,opt,name=won,proto3" json:"won,omitempty"`
	Converted     bool                   `protobuf:"varint,6,opt,name=converted,proto3" json:"converted,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserSegment   *UserSegment           `protobuf:"bytes,8,opt,name=user_segment,json=userSegment,proto3" json:"user_segment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRecord) Reset() {
	*x = BidRecord{}
	mi := &file_api_proto_bidding_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRecord) ProtoMessage() {}

func (x *BidRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRecord.ProtoReflect.Descriptor instead.
func (*BidRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{7}
}

func (x *BidRecord) GetBidId() string {
	if x != nil {
		return x.BidId
	}
	return ""
}

func (x *BidRecord) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *BidRecord) GetBidPrice() float64 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (x *BidRecord) GetWinPrice() float64 {
	if x != nil {
		return x.WinPrice
	}
	return 0
}

func (x *BidRecord) GetWon() bool {
	if x != nil {
		return x.Won
	}
	return false
}

func (x *BidRecord) GetConverted() bool {
	if x != nil {
		return x.Converted
	}
	return false
}

func (x *BidRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BidRecord) GetUserSegment() *UserSegment {
	if x != nil {
		return x.UserSegment
	}
	return nil
}

// StreamRequest for real-time bid updates
type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignIds   []string               `protobuf:"bytes,1,rep,name=campaign_ids,json=campaignIds,proto3" json:"campaign_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_api_proto_bidding_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{8}
}

func (x *StreamRequest) GetCampaignIds() []string {
	if x != nil {
		return x.CampaignIds
	}
	return nil
}

// BidUpdate for streaming real-time updates
type BidUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CampaignId     string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	CurrentBidRate float64                `protobuf:"fixed64,2,opt,name=current_bid_rate,json=currentBidRate,proto3" json:"current_bid_rate,omitempty"`
	WinRate        float64                `protobuf:"fixed64,3,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	ConversionRate float64                `protobuf:"fixed64,4,opt,name=conversion_rate,json=conversionRate,proto3" json:"conversion_rate,omitempty"`
	SpendRate      float64                `protobuf:"fixed64,5,opt,name=spend_rate,json=spendRate,proto3" json:"spend_rate,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BidUpdate) Reset() {
	*x = BidUpdate{}
	mi := &file_api_proto_bidding_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidUpdate) ProtoMessage() {}

func (x *BidUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidUpdate.ProtoReflect.Descriptor instead.
func (*BidUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{9}
}

func (x *BidUpdate) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *BidUpdate) GetCurrentBidRate() float64 {
	if x != nil {
		return x.CurrentBidRate
	}
	return 0
}

func (x *BidUpdate) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *BidUpdate) GetConversionRate() float64 {
	if x != nil {
		return x.ConversionRate
	}
	return 0
}

func (x *BidUpdate) GetSpendRate() float64 {
	if x != nil {
		return x.SpendRate
	}
	return 0
}

func (x *BidUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// CampaignStatsRequest for campaign analytics
type CampaignStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignStatsRequest) Reset() {
	*x = CampaignStatsRequest{}
	mi := &file_api_proto_bidding_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignStatsRequest) ProtoMessage() {}

func (x *CampaignStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignStatsRequest.ProtoReflect.Descriptor instead.
func (*CampaignStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{10}
}

func (x *CampaignStatsRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *CampaignStatsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CampaignStatsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// CampaignStatsResponse contains campaign performance metrics
type CampaignStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CampaignId        string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	TotalBids         int64                  `protobuf:"varint,2,opt,name=total_bids,json=totalBids,proto3" json:"total_bids,omitempty"`
	WonBids           int64                  `protobuf:"varint,3,opt,name=won_bids,json=wonBids,proto3" json:"won_bids,omitempty"`
	Conversions       int64                  `protobuf:"varint,4,opt,name=conversions,proto3" json:"conversions,omitempty"`
	TotalSpend        float64                `protobuf:"fixed64,5,opt,name=total_spend,json=totalSpend,proto3" json:"total_spend,omitempty"`
	AverageBid        float64                `protobuf:"fixed64,6,opt,name=average_bid,json=averageBid,proto3" json:"average_bid,omitempty"`
	WinRate           float64                `protobuf:"fixed64,7,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	ConversionRate    float64                `protobuf:"fixed64,8,opt,name=conversion_rate,json=conversionRate,proto3" json:"conversion_rate,omitempty"`
	CostPerConversion float64                `protobuf:"fixed64,9,opt,name=cost_per_conversion,json=costPerConversion,proto3" json:"cost_per_conversion,omitempty"`
	ReturnOnAdSpend   float64                `protobuf:"fixed64,10,opt,name=return_on_ad_spend,json=returnOnAdSpend,proto3" json:"return_on_ad_spend,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CampaignStatsResponse) Reset() {
	*x = CampaignStatsResponse{}
	mi := &file_api_proto_bidding_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignStatsResponse) ProtoMessage() {}

func (x *CampaignStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignStatsResponse.ProtoReflect.Descriptor instead.
func (*CampaignStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{11}
}

func (x *CampaignStatsResponse) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *CampaignStatsResponse) GetTotalBids() int64 {
	if x != nil {
		return x.TotalBids
	}
	return 0
}

func (x *CampaignStatsResponse) GetWonBids() int64 {
	if x != nil {
		return x.WonBids
	}
	return 0
}

func (x *CampaignStatsResponse) GetConversions() int64 {
	if x != nil {
		return x.Conversions
	}
	return 0
}

func (x *CampaignStatsResponse) GetTotalSpend() float64 {
	if x != nil {
		return x.TotalSpend
	}
	return 0
}

func (x *CampaignStatsResponse) GetAverageBid() float64 {
	if x != nil {
		return x.AverageBid
	}
	return 0
}

func (x *CampaignStatsResponse) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *CampaignStatsResponse) GetConversionRate() float64 {
	if x != nil {
		return x.ConversionRate
	}
	return 0
}

func (x *CampaignStatsResponse) GetCostPerConversion() float64 {
	if x != nil {
		return x.CostPerConversion
	}
	return 0
}

func (x *CampaignStatsResponse) GetReturnOnAdSpend() float64 {
	if x != nil {
		return x.ReturnOnAdSpend
	}
	return 0
}

// FraudAlertsRequest for fraud detection queries
type FraudAlertsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StartTime         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SeverityThreshold int32                  `protobuf:"varint,3,opt,name=severity_threshold,json=severityThreshold,proto3" json:"severity_threshold,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FraudAlertsRequest) Reset() {
	*x = FraudAlertsRequest{}
	mi := &file_api_proto_bidding_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudAlertsRequest) ProtoMessage() {}

func (x *FraudAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudAlertsRequest.ProtoReflect.Descriptor instead.
func (*FraudAlertsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{12}
}

func (x *FraudAlertsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *FraudAlertsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *FraudAlertsRequest) GetSeverityThreshold() int32 {
	if x != nil {
		return x.SeverityThreshold
	}
	return 0
}

// FraudAlertsResponse contains detected fraud patterns
type FraudAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*FraudAlert          `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudAlertsResponse) Reset() {
	*x = FraudAlertsResponse{}
	mi := &file_api_proto_bidding_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudAlertsResponse) ProtoMessage() {}

func (x *FraudAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudAlertsResponse.ProtoReflect.Descriptor instead.
func (*FraudAlertsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{13}
}

func (x *FraudAlertsResponse) GetAlerts() []*FraudAlert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

// FraudAlert represents a detected fraud pattern
type FraudAlert struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AlertId         string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	CampaignId      string                 `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	AlertType       string                 `protobuf:"bytes,3,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"` // click_fraud, impression_fraud, conversion_fraud
	Severity        int32                  `protobuf:"varint,4,opt,name=severity,proto3" json:"severity,omitempty"`                   // 1-10 scale
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	DetectedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	AffectedUserIds []string               `protobuf:"bytes,7,rep,name=affected_user_ids,json=affectedUserIds,proto3" json:"affected_user_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FraudAlert) Reset() {
	*x = FraudAlert{}
	mi := &file_api_proto_bidding_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudAlert) ProtoMessage() {}

func (x *FraudAlert) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudAlert.ProtoReflect.Descriptor instead.
func (*FraudAlert) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{14}
}

func (x *FraudAlert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *FraudAlert) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *FraudAlert) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *FraudAlert) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *FraudAlert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FraudAlert) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

func (x *FraudAlert) GetAffectedUserIds() []string {
	if x != nil {
		return x.AffectedUserIds
	}
	return nil
}

// AccuracyRequest for ML model performance
type AccuracyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccuracyRequest) Reset() {
	*x = AccuracyRequest{}
	mi := &file_api_proto_bidding_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccuracyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccuracyRequest) ProtoMessage() {}

func (x *AccuracyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccuracyRequest.ProtoReflect.Descriptor instead.
func (*AccuracyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{15}
}

func (x *AccuracyRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *AccuracyRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *AccuracyRequest) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

// AccuracyResponse contains model performance metrics
type AccuracyResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PredictionAccuracy  float64                `protobuf:"fixed64,1,opt,name=prediction_accuracy,json=predictionAccuracy,proto3" json:"prediction_accuracy,omitempty"`
	MeanAbsoluteError   float64                `protobuf:"fixed64,2,opt,name=mean_absolute_error,json=meanAbsoluteError,proto3" json:"mean_absolute_error,omitempty"`
	RootMeanSquareError float64                `protobuf:"fixed64,3,opt,name=root_mean_square_error,json=rootMeanSquareError,proto3" json:"root_mean_square_error,omitempty"`
	TotalPredictions    int64                  `protobuf:"varint,4,opt,name=total_predictions,json=totalPredictions,proto3" json:"total_predictions,omitempty"`
	ModelVersion        string                 `protobuf:"bytes,5,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AccuracyResponse) Reset() {
	*x = AccuracyResponse{}
	mi := &file_api_proto_bidding_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccuracyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccuracyResponse) ProtoMessage() {}

func (x *AccuracyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bidding_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccuracyResponse.ProtoReflect.Descriptor instead.
func (*AccuracyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bidding_proto_rawDescGZIP(), []int{16}
}

func (x *AccuracyResponse) GetPredictionAccuracy() float64 {
	if x != nil {
		return x.PredictionAccuracy
	}
	return 0
}

func (x *AccuracyResponse) GetMeanAbsoluteError() float64 {
	if x != nil {
		return x.MeanAbsoluteError
	}
	return 0
}

func (x *AccuracyResponse) GetRootMeanSquareError() float64 {
	if x != nil {
		return x.RootMeanSquareError
	}
	return 0
}

func (x *AccuracyResponse) GetTotalPredictions() int64 {
	if x != nil {
		return x.TotalPredictions
	}
	return 0
}

func (x *AccuracyResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

var File_api_proto_bidding_proto protoreflect.FileDescriptor

const file_api_proto_bidding_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/bidding.proto\x12\abidding\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x02\n" +
	"\n" +
	"BidRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x127\n" +
	"\fuser_segment\x18\x03 \x01(\v2\x14.bidding.UserSegmentR\vuserSegment\x127\n" +
	"\fgeo_location\x18\x04 \x01(\v2\x14.bidding.GeoLocationR\vgeoLocation\x124\n" +
	"\vdevice_info\x18\x05 \x01(\v2\x13.bidding.DeviceInfoR\n" +
	"deviceInfo\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vfloor_price\x18\a \x01(\x01R\n" +
	"floorPrice\x12\x1a\n" +
	"\bkeywords\x18\b \x03(\tR\bkeywords\"\xaa\x01\n" +
	"\vBidResponse\x12\x1b\n" +
	"\tbid_price\x18\x01 \x01(\x01R\bbidPrice\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\x12\x1d\n" +
	"\n" +
	"fraud_risk\x18\x04 \x01(\bR\tfraudRisk\x12#\n" +
	"\rprediction_id\x18\x05 \x01(\tR\fpredictionId\"\xaa\x01\n" +
	"\vUserSegment\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12)\n" +
	"\x10engagement_score\x18\x03 \x01(\x01R\x0fengagementScore\x125\n" +
	"\x16conversion_probability\x18\x04 \x01(\x01R\x15conversionProbability\"\x8d\x01\n" +
	"\vGeoLocation\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\"t\n" +
	"\n" +
	"DeviceInfo\x12\x1f\n" +
	"\vdevice_type\x18\x01 \x01(\tR\n" +
	"deviceType\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x18\n" +
	"\abrowser\x18\x03 \x01(\tR\abrowser\x12\x1b\n" +
	"\tis_mobile\x18\x04 \x01(\bR\bisMobile\"\xd4\x01\n" +
	"\x11BidHistoryRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"]\n" +
	"\x12BidHistoryResponse\x12&\n" +
	"\x04bids\x18\x01 \x03(\v2\x12.bidding.BidRecordR\x04bids\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xa0\x02\n" +
	"\tBidRecord\x12\x15\n" +
	"\x06bid_id\x18\x01 \x01(\tR\x05bidId\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\tR\n" +
	"campaignId\x12\x1b\n" +
	"\tbid_price\x18\x03 \x01(\x01R\bbidPrice\x12\x1b\n" +
	"\twin_price\x18\x04 \x01(\x01R\bwinPrice\x12\x10\n" +
	"\x03won\x18\x05 \x01(\bR\x03won\x12\x1c\n" +
	"\tconverted\x18\x06 \x01(\bR\tconverted\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x127\n" +
	"\fuser_segment\x18\b \x01(\v2\x14.bidding.UserSegmentR\vuserSegment\"2\n" +
	"\rStreamRequest\x12!\n" +
	"\fcampaign_ids\x18\x01 \x03(\tR\vcampaignIds\"\xf3\x01\n" +
	"\tBidUpdate\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12(\n" +
	"\x10current_bid_rate\x18\x02 \x01(\x01R\x0ecurrentBidRate\x12\x19\n" +
	"\bwin_rate\x18\x03 \x01(\x01R\awinRate\x12'\n" +
	"\x0fconversion_rate\x18\x04 \x01(\x01R\x0econversionRate\x12\x1d\n" +
	"\n" +
	"spend_rate\x18\x05 \x01(\x01R\tspendRate\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa9\x01\n" +
	"\x14CampaignStatsRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xf7\x02\n" +
	"\x15CampaignStatsResponse\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x1d\n" +
	"\n" +
	"total_bids\x18\x02 \x01(\x03R\ttotalBids\x12\x19\n" +
	"\bwon_bids\x18\x03 \x01(\x03R\awonBids\x12 \n" +
	"\vconversions\x18\x04 \x01(\x03R\vconversions\x12\x1f\n" +
	"\vtotal_spend\x18\x05 \x01(\x01R\n" +
	"totalSpend\x12\x1f\n" +
	"\vaverage_bid\x18\x06 \x01(\x01R\n" +
	"averageBid\x12\x19\n" +
	"\bwin_rate\x18\a \x01(\x01R\awinRate\x12'\n" +
	"\x0fconversion_rate\x18\b \x01(\x01R\x0econversionRate\x12.\n" +
	"\x13cost_per_conversion\x18\t \x01(\x01R\x11costPerConversion\x12+\n" +
	"\x12return_on_ad_spend\x18\n" +
	" \x01(\x01R\x0freturnOnAdSpend\"\xb5\x01\n" +
	"\x12FraudAlertsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12-\n" +
	"\x12severity_threshold\x18\x03 \x01(\x05R\x11severityThreshold\"B\n" +
	"\x13FraudAlertsResponse\x12+\n" +
	"\x06alerts\x18\x01 \x03(\v2\x13.bidding.FraudAlertR\x06alerts\"\x8e\x02\n" +
	"\n" +
	"FraudAlert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\tR\n" +
	"campaignId\x12\x1d\n" +
	"\n" +
	"alert_type\x18\x03 \x01(\tR\talertType\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\x05R\bseverity\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12;\n" +
	"\vdetected_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\x12*\n" +
	"\x11affected_user_ids\x18\a \x03(\tR\x0faffectedUserIds\"\xa8\x01\n" +
	"\x0fAccuracyRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\"\xfa\x01\n" +
	"\x10AccuracyResponse\x12/\n" +
	"\x13prediction_accuracy\x18\x01 \x01(\x01R\x12predictionAccuracy\x12.\n" +
	"\x13mean_absolute_error\x18\x02 \x01(\x01R\x11meanAbsoluteError\x123\n" +
	"\x16root_mean_square_error\x18\x03 \x01(\x01R\x13rootMeanSquareError\x12+\n" +
	"\x11total_predictions\x18\x04 \x01(\x03R\x10totalPredictions\x12#\n" +
	"\rmodel_version\x18\x05 \x01(\tR\fmodelVersion2\xd5\x01\n" +
	"\x0eBiddingService\x127\n" +
	"\n" +
	"ProcessBid\x12\x13.bidding.BidRequest\x1a\x14.bidding.BidResponse\x12H\n" +
	"\rGetBidHistory\x12\x1a.bidding.BidHistoryRequest\x1a\x1b.bidding.BidHistoryResponse\x12@\n" +
	"\x10StreamBidUpdates\x12\x16.bidding.StreamRequest\x1a\x12.bidding.BidUpdate0\x012\x80\x02\n" +
	"\x10AnalyticsService\x12Q\n" +
	"\x10GetCampaignStats\x12\x1d.bidding.CampaignStatsRequest\x1a\x1e.bidding.CampaignStatsResponse\x12K\n" +
	"\x0eGetFraudAlerts\x12\x1b.bidding.FraudAlertsRequest\x1a\x1c.bidding.FraudAlertsResponse\x12L\n" +
	"\x15GetPredictionAccuracy\x12\x18.bidding.AccuracyRequest\x1a\x19.bidding.AccuracyResponseB/Z-github.com/baskint/bidding-analysis/api/protob\x06proto3"

var (
	file_api_proto_bidding_proto_rawDescOnce sync.Once
	file_api_proto_bidding_proto_rawDescData []byte
)

func file_api_proto_bidding_proto_rawDescGZIP() []byte {
	file_api_proto_bidding_proto_rawDescOnce.Do(func() {
		file_api_proto_bidding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_bidding_proto_rawDesc), len(file_api_proto_bidding_proto_rawDesc)))
	})
	return file_api_proto_bidding_proto_rawDescData
}

var file_api_proto_bidding_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_proto_bidding_proto_goTypes = []any{
	(*BidRequest)(nil),            // 0: bidding.BidRequest
	(*BidResponse)(nil),           // 1: bidding.BidResponse
	(*UserSegment)(nil),           // 2: bidding.UserSegment
	(*GeoLocation)(nil),           // 3: bidding.GeoLocation
	(*DeviceInfo)(nil),            // 4: bidding.DeviceInfo
	(*BidHistoryRequest)(nil),     // 5: bidding.BidHistoryRequest
	(*BidHistoryResponse)(nil),    // 6: bidding.BidHistoryResponse
	(*BidRecord)(nil),             // 7: bidding.BidRecord
	(*StreamRequest)(nil),         // 8: bidding.StreamRequest
	(*BidUpdate)(nil),             // 9: bidding.BidUpdate
	(*CampaignStatsRequest)(nil),  // 10: bidding.CampaignStatsRequest
	(*CampaignStatsResponse)(nil), // 11: bidding.CampaignStatsResponse
	(*FraudAlertsRequest)(nil),    // 12: bidding.FraudAlertsRequest
	(*FraudAlertsResponse)(nil),   // 13: bidding.FraudAlertsResponse
	(*FraudAlert)(nil),            // 14: bidding.FraudAlert
	(*AccuracyRequest)(nil),       // 15: bidding.AccuracyRequest
	(*AccuracyResponse)(nil),      // 16: bidding.AccuracyResponse
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_api_proto_bidding_proto_depIdxs = []int32{
	2,  // 0: bidding.BidRequest.user_segment:type_name -> bidding.UserSegment
	3,  // 1: bidding.BidRequest.geo_location:type_name -> bidding.GeoLocation
	4,  // 2: bidding.BidRequest.device_info:type_name -> bidding.DeviceInfo
	17, // 3: bidding.BidRequest.timestamp:type_name -> google.protobuf.Timestamp
	17, // 4: bidding.BidHistoryRequest.start_time:type_name -> google.protobuf.Timestamp
	17, // 5: bidding.BidHistoryRequest.end_time:type_name -> google.protobuf.Timestamp
	7,  // 6: bidding.BidHistoryResponse.bids:type_name -> bidding.BidRecord
	17, // 7: bidding.BidRecord.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 8: bidding.BidRecord.user_segment:type_name -> bidding.UserSegment
	17, // 9: bidding.BidUpdate.timestamp:type_name -> google.protobuf.Timestamp
	17, // 10: bidding.CampaignStatsRequest.start_time:type_name -> google.protobuf.Timestamp
	17, // 11: bidding.CampaignStatsRequest.end_time:type_name -> google.protobuf.Timestamp
	17, // 12: bidding.FraudAlertsRequest.start_time:type_name -> google.protobuf.Timestamp
	17, // 13: bidding.FraudAlertsRequest.end_time:type_name -> google.protobuf.Timestamp
	14, // 14: bidding.FraudAlertsResponse.alerts:type_name -> bidding.FraudAlert
	17, // 15: bidding.FraudAlert.detected_at:type_name -> google.protobuf.Timestamp
	17, // 16: bidding.AccuracyRequest.start_time:type_name -> google.protobuf.Timestamp
	17, // 17: bidding.AccuracyRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 18: bidding.BiddingService.ProcessBid:input_type -> bidding.BidRequest
	5,  // 19: bidding.BiddingService.GetBidHistory:input_type -> bidding.BidHistoryRequest
	8,  // 20: bidding.BiddingService.StreamBidUpdates:input_type -> bidding.StreamRequest
	10, // 21: bidding.AnalyticsService.GetCampaignStats:input_type -> bidding.CampaignStatsRequest
	12, // 22: bidding.AnalyticsService.GetFraudAlerts:input_type -> bidding.FraudAlertsRequest
	15, // 23: bidding.AnalyticsService.GetPredictionAccuracy:input_type -> bidding.AccuracyRequest
	1,  // 24: bidding.BiddingService.ProcessBid:output_type -> bidding.BidResponse
	6,  // 25: bidding.BiddingService.GetBidHistory:output_type -> bidding.BidHistoryResponse
	9,  // 26: bidding.BiddingService.StreamBidUpdates:output_type -> bidding.BidUpdate
	11, // 27: bidding.AnalyticsService.GetCampaignStats:output_type -> bidding.CampaignStatsResponse
	13, // 28: bidding.AnalyticsService.GetFraudAlerts:output_type -> bidding.FraudAlertsResponse
	16, // 29: bidding.AnalyticsService.GetPredictionAccuracy:output_type -> bidding.AccuracyResponse
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_proto_bidding_proto_init() }
func file_api_proto_bidding_proto_init() {
	if File_api_proto_bidding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_bidding_proto_rawDesc), len(file_api_proto_bidding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_bidding_proto_goTypes,
		DependencyIndexes: file_api_proto_bidding_proto_depIdxs,
		MessageInfos:      file_api_proto_bidding_proto_msgTypes,
	}.Build()
	File_api_proto_bidding_proto = out.File
	file_api_proto_bidding_proto_goTypes = nil
	file_api_proto_bidding_proto_depIdxs = nil
}
